# Generated by Django 3.0.7 on 2020-07-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('name', models.TextField()),
                ('quantity', models.DecimalField(decimal_places=0, max_digits=4)),
                ('category', models.CharField(choices=[('beer', 'Beer'), ('whiskey', 'Whiskey'), ('wine', 'Wine'), ('vodka', 'Vodka'), ('spirits', 'Spirits')], default='beer', max_length=7)),
            ],
        ),
    ]
